server:
    port: ${SERVER_PORT:8080}
    
spring:
    application:
        name: ${APPLICATION_NAME:events-management-system}
    datasource:
        url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:ems}
        username: ${DATABASE_USERNAME:root}
        password: ${DATABASE_PASSWORD:root}
    jpa:
        show-sql: ${JPA_SHOW_SQL:true}
        properties:
            hibernate:
                format_sql: ${HIBERNATE_FORMAT_SQL:true}
        hibernate:
            ddl-auto: update
    mail:
        host: ${MAIL_HOST_NAME:smtp.gmail.com}
        port: ${MAIL_PORT:587}
        username: ${GMAIL_USERNAME:prince08833@gmail.com}
        password: ${GMAIL_APP_PASSWORD:zmkv mfwf xhjz jyuo}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
              
com:
    learn:
        cloudinary:
            name: ${CLOUDINARY_NAME:duhumawiq}
            api:
                key: ${CLOUDINARY_API_KEY:119948159122814}
                secret: ${CLOUDINARY_API_SECRET:dVF_AkcNk985SqZQcDBYErDHDZI}
                
logging:
    level:
        org:
            springframework:
                security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
    pattern:
        console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}